parameters:
- name: env
  type: string
  default: test

stages:
  - stage: plan
    displayName: Plan environment
    jobs:
      - job: plan
        displayName: Plan infrastructure
        steps:

          - template: init.yml
            parameters:
              env: ${{ parameters.env }}

          - task: Bash@3
            displayName: Create dummy ssh key file
            inputs:
              workingDirectory: infrastructure
              targetType: 'inline'
              script: |
                rm -rf keys
                mkdir keys
                touch keys/key.pub
                ls keys

          - task: Bash@3
            inputs:
              workingDirectory: infrastructure
              targetType: 'inline'
              script: terraform plan -var-file=${{ parameters.env }}/env.tfvars
            displayName: Plan Terraform ${{ parameters.env }}
            env:
              ARM_CLIENT_ID: $(arm_client_id)
              ARM_CLIENT_SECRET: $(arm_client_secret)
              ARM_TENANT_ID: $(arm_tenant_id)
              ARM_SUBSCRIPTION_ID: $(arm_subscription_id)

  - stage: apply
    displayName: Deploy environment
    jobs:
      - deployment: apply
        displayName: Deploy to environment
        environment: ${{ parameters.env }}
        strategy:
          runOnce:
            deploy:
              steps:

                - template: init.yml
                  parameters:
                    env: ${{ parameters.env }}

                - task: Bash@3
                  displayName: Create ssh key file
                  inputs:
                    workingDirectory: infrastructure
                    targetType: 'inline'
                    script: |
                      rm -rf keys
                      mkdir keys
                      ssh-keygen -t rsa -b 4098 -P "" -f keys/key
                      ls keys

                - task: Bash@3
                  inputs:
                    workingDirectory: infrastructure
                    targetType: 'inline'
                    script: terraform apply -var-file=${{ parameters.env }}/env.tfvars -auto-approve
                  displayName: Apply Terraform ${{ parameters.env }}
                  env:
                    ARM_CLIENT_ID: $(arm_client_id)
                    ARM_CLIENT_SECRET: $(arm_client_secret)
                    ARM_TENANT_ID: $(arm_tenant_id)
                    ARM_SUBSCRIPTION_ID: $(arm_subscription_id)
