trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: env
  displayName: Targeted environment
  type: string
  values:
  - test
  - dev
  - prod

variables:
  - group: service_principals

jobs:
  - deployment: destroy
    displayName: Destroy environment
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:

            - checkout: self
              clean: true

            - template: templates/init.yml
              parameters:
                env: ${{ parameters.env }}

            - template: templates/dummy_ssh.yml

            - task: Bash@3
              inputs:
                workingDirectory: infrastructure
                targetType: 'inline'
                script: terraform destroy -var-file=${{ parameters.env }}/env.tfvars -auto-approve
              displayName: Destroy Terraform ${{ parameters.env }}
              env:
                ARM_CLIENT_ID: $(arm_client_id)
                ARM_CLIENT_SECRET: $(arm_client_secret)
                ARM_TENANT_ID: $(arm_tenant_id)
                ARM_SUBSCRIPTION_ID: $(arm_subscription_id)
