trigger:
  paths:
    include:
    - infrastructure/

variables:
  - group: service_principals

pool:
  vmImage: 'ubuntu-latest'

strategy:
  maxParallel: 3
  matrix:
    test:
      env: test
    dev:
      env: dev
    prod:
      env: prod

steps:
  - template: templates/dummy_ssh.yml

  - template: templates/init.yml
    parameters:
      stage: $(env)

  - task: Bash@3
    inputs:
      workingDirectory: infrastructure
      targetType: 'inline'
      script: terraform validate
    displayName: Validate Terraform
