trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: stage
  displayName:
  type: string
  values:
  - test
  - dev
  - prod

variables:
  - group: service_principals
  # Not used, but required to be set
  - name: tf_var_os_user
    value: username

steps:
  - template: templates/init.yml

  - bash: terraform destroy -var-file=${{ parameters.stage }}/env.tfvars -auto-approve
    displayName: Destroy Terraform ${{ parameters.stage }}
    workingDirectory: infrastructure
