trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - infrastructure/
    exclude:
      - infrastructure/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: service_principals
  - name: env
    value: dev

stages:
  - template: templates/deploy.yml
    parameters:
      env: $(env)
