trigger:
  branches:
    include:
      - prod
  paths:
    include:
      - infrastructure/
    exclude:
      - infrastructure/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: service_principals
  - name: stage
    value: prod

steps:
  - template: templates/apply.yml
    parameters:
      stage: $(stage)
