trigger:
  branches:
    include:
      - test
  paths:
    include:
      - infrastructure/
    exclude:
      - infrastructure/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: service_principals
  - name: stage
    value: test

stages:
  - stage: plan
    jobs:
      - job: plan
        steps:
          - bash: |
              mkdir keys
              touch keys/key.pub
              ls keys
            displayName: Create dummy ssh key file
            workingDirectory: infrastructure

          - template: templates/plan.yml
            parameters:
              stage: $(stage)

  - stage: apply
    jobs:
      - job: apply
        steps:
          - bash: |
              mkdir keys
              ssh-keygen -t rsa -b 4098 -P "" -f keys/key
              ls keys

          - template: templates/apply.yml
            parameters:
              stage: $(stage)
