trigger:
  branches:
    include:
      - test
  paths:
    include:
      - infrastructure/
    exclude:
      - infrastructure/azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: service_principals
  - name: env
    value: test

parameters:
  - name: plan
    displayName: Run infrastructure plan?
    type: boolean
    default: true
  - name: infrastructure
    displayName: Run infrastructure deployment?
    type: boolean
    default: true
  - name: configuration
    displayName: Run configuration provision?
    type: boolean
    default: true

stages:
  - template: templates/deploy.yml
    parameters:
      env: $(env)
      plan: ${{ plan }}
      infrastructure: ${{ infrastructure }}
      configuration: ${{ configuration }}
