trigger:
  paths:
    include:
    - infrastructure/

variables:
  - group: service_principals

pool:
  vmImage: 'ubuntu-latest'

strategy:
  maxParallel: 3
  matrix:
    test:
      stage: test
    dev:
      stage: dev
    prod:
      stage: prod

steps:
- bash: touch server.pub
  displayName: Create dummy required file
  workingDirectory: infrastructure

- bash: terraform init -backend-config=$(stage)/backend.tfvars
  displayName: Initilise Terraform
  workingDirectory: infrastructure

- bash: terraform validate
  displayName: Validate Terraform
  workingDirectory: infrastructure
