trigger:
  paths:
    include:
    - infrastructure/

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    touch server.pub
    echo "subscription_id = \"fakesubid\"
    tenant_id = \"faketenantid\"
    client_id = \"fakeclientid\"
    client_secret = \"fakeclientsecret\"
    os_user = \"fakeosuser\"
    " >> secrets.auto.tfvars
  displayName: Create dummy required files

- bash: terraform init
  displayName: Initilise Terraform

- bash: terraform validate
  displayName: Validate Terraform
