---
- name: Dynamically load server IP into internal hosts from input var
  hosts: localhost
  tasks:

    - name: Add target IP to internal hosts
      add_host:
        name: "{{ target_server }}"
        group: servers

- name: Configuration as Code
  hosts: servers
  become: yes
  tasks:
    - name: Update system packages
      apt:
        name: "*"
        state: latest

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
